#+TITLE: Install and compile pico-sdk on debian systems
* About
install-pico-debian.sh is a bash installed script,
which is derived from the pico-setup.sh script from https://gihub.com/raspberrypi/pico-setup.

* LICENSE

BSD-3-Clause

The <owner> is Thomas W. Rake
The <year> is 2025

** The orginical code

This a derividive work of the file [[https://github.com/raspberrypi/pico-setup/blob/master/pico_setup.sh][pico_setup.sh]] from the [[https://github.com/raspberrypi/pico-setup][this github repository]], the *orginial code*  that repository contained no license information.
I beleive in keeping pattern of Raspberry Pi the copyright of the *original code* is held by Raspberry Pi (Trading) Ltd.
The authors of [[https://github.com/raspberrypi/pico-setup/blob/master/pico_setup.sh][pico_setup.sh]] are various contributers list on that repo.
** The owner fo the original code
The owner of the *original code* is Raspberry PI (Trading) Ltd

As witness I reference  [[https://github.com/raspberrypi/pico-sdk/blob/master/src/boards/include/boards/pico.h][pico.h]] file and note of the Raspberry PI, pico-sdk:
#+begin_src emacs-lisp
/*
 * Copyright (c) 2020 Raspberry Pi (Trading) Ltd.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
#+end_src

* Philosophy
The *original code* outlines a method for installing code and compiling tools on a Debian-based OS system using Raspberry Pi hardware.
Based on the method in the *original code*, this code does a similar task for AMD64 systems.
The cross-compilation toolchains needed for are also included in the installation.


* Features of the *original code*
- A central *pico* location for installation.
- Exporting environment locations of the *original code* are included in ~/.bashrc file.

* Additional Features
- Abandon apt dependencies installation of *original code* in favor of installation failure.
- Create a pico-toolchain directory as a subdirectory of *pico*.
- Create additional environment locations in ~/.bashrc for markers of the compiled tools such as picotool and openocd.

* Debian Packages used

On December 7, 2025, I upgraded my laptop to Debian Trixie. During that installation, the packages used to support pico-debians-setup.sh

I am using KDE/Plasma as my Desktop OS.

Packages I installed
- build-essential
- automake
- python3
- python3-pip
- pyhton3-virtualdenv
- KDE
- openssh-server
- keepassxc
- emacs
- ninja-build
- curl
- libtool
- libtool-bin
- libjim-dev
- pkg-config
- libusb-1.0-0
- libusb-1.0-0-dev
- minicom


